### ISSUE TITLE
ClientNames or ClientName?

### ISSUE THREAD

**Issue by JensSpanier** [win-acme/win-acme.github.io#7]
The documentations says [ClientNames](https://github.com/win-acme/win-acme.github.io/blob/master/reference/settings.md#clientnames), but the settings.json says [ClientName](https://github.com/win-acme/win-acme/blob/master/src/main/settings.json#L3).

Are both possible?

**Comment by WouterTinus** [comment]
It's `ClientName`, it was `ClientNames` for 1.9.x at some point, but that was really just a hack to handle the rename from letsencrypt-win-simple to win-acme. I'll update the docs!
